### ISSUE TITLE
Unhandled error with Bitfinex: "Error local variable 'ticker' referenced before assignment"

### ISSUE THREAD

**Issue by agramajo** [BitBotFactory/poloniexlendingbot#466] opened 2017-08-17 21:17 UTC
LOG:

2017-08-17 12:12:38 Error local variable 'ticker' referenced before assignment
Traceback (most recent call last):
  File "lendingbot.py", line 90, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "/root/poloniexlendingbot.2/modules/Data.py", line 85, in update_conversion_rates
    ticker_response = api.return_ticker()
  File "/root/poloniexlendingbot.2/modules/Bitfinex.py", line 149, in return_ticker
    if 'message' in ticker:
UnboundLocalError: local variable 'ticker' referenced before assignment

Unhandled error, please open a Github issue so we can fix it!

**Comment by mad366** [comment] 2017-08-19 07:19
Same for me this night (Bitfinex):

2017-08-19 07:48:00 Error local variable 'ticker' referenced before assignment
Traceback (most recent call last):
  File "lendingbot.py", line 90, in <module>
    Data.update_conversion_rates(output_currency, json_output_enabled)
  File "/home/pi/poloniex/modules/Data.py", line 85, in update_conversion_rates
    ticker_response = api.return_ticker()
  File "/home/pi/poloniex/modules/Bitfinex.py", line 149, in return_ticker
    if 'message' in ticker:
UnboundLocalError: local variable 'ticker' referenced before assignment

Unhandled error, please open a Github issue so we can fix it!
Traceback (most recent call last):
  File "lendingbot.py", line 136, in <module>
    if notify_conf['notify_caught_exception']:
KeyError: 'notify_caught_exception'

**Comment by mike4001** [comment] 2017-08-19 14:41
Same here.

Also left a comment about it here: https://github.com/BitBotFactory/poloniexlendingbot/issues/471

It´s now at a point where I cannot run the bot for 30 min without it stopping to work because of this error :-/

**Comment by vitormilano** [comment] 2017-08-19 22:37
Same here. It won't create any orders at Bitfinex at this time as it seems.
Thinking on moving to Polo.

**Comment by mad366** [comment] 2017-08-20 05:44
Yeah... need to restart bot several times per day. It's annoying.

**Comment by utdrmac** [comment] 2017-08-20 21:21
It's so weird that you guys have to restart your bot. I too have received this exact error several times but my bot just keeps on trucking along. Are you guys on Windows or something "odd"? I'm just on standard linux running the bot inside a `screen` session.

**Comment by utdrmac** [comment] 2017-08-20 21:36
@agramajo @mad366 @vitormilano @mike4001 Please test out this fix for me.
Add `ticker = None` right above the 'try' inside modules/Bitfinex.py so that it looks like this:

```
                  couple = (base + '_' + curr)
                  coupleReverse = (curr + '_' + base)

                  ticker = None
                  try:
                      ticker = self._get('pubticker/'+symbol)
                  except ApiError as e:
```

**Comment by mike4001** [comment] 2017-08-20 21:48
@utdrmac I am running the bot on a Raspberry Pi

Have just added the code line and startet the bot.

Will let you know if it stops again but this could take some time. Could also run the bot for hours before it stopped because of the ticker error

**Comment by Beppe1988** [comment] 2017-08-20 21:56
I tried to solve this adding this line:

> global ticker

under line 126 in Bitfinex.py

> def return_ticker(self):

**Comment by utdrmac** [comment] 2017-08-20 22:11
@Beppe1988 it would be better to not make this global, programmatically speaking. It "is" a local variable for this function and should not be treated object-wide

**Comment by mad366** [comment] 2017-08-21 06:35
@utdrmac added and testing started. Let you know about results in 24h. Thank you!

**Comment by mike4001** [comment] 2017-08-21 06:42
My bot now stopped with the error message

2017-08-21 00:36:56 Error argument of type 'NoneType' is not iterable

error.txt says

Traceback (most recent call last):
  File "lendingbot.py", line 136, in <module>
    if notify_conf['notify_caught_exception']:
KeyError: 'notify_caught_exception'

**Comment by utdrmac** [comment] 2017-08-21 06:56
@mike4001 that's a different error not associated with this issue. There's a PR and a separate issue for that KeyError.

**Comment by rnevet** [comment] 2017-08-21 08:04
'notify_caught_exception' fix has been merged.

**Comment by CyberBaby** [comment] 2017-08-21 08:18
#477

**Comment by Beppe1988** [comment] 2017-08-21 14:00
thank you!

**Comment by mad366** [comment] 2017-08-22 04:26
@utdrmac I can confirm that this issue is fixed. Thank you!

**Comment by mike4001** [comment] 2017-08-22 06:53
Bot isn't stopping for me either anymore.

**Comment by utdrmac** [comment] 2017-10-23 18:55
@rnevet I think this can be closed. It should have auto-closed on the merge.

**Closed** 2017-10-23 20:42 UTC
