### ISSUE TITLE
Verbose account stats before first closed loan on Bitfinex

### ISSUE THREAD

**Issue by pedrofaraco** [BitBotFactory/poloniexlendingbot#488] opened 2017-08-24 14:33 UTC
Right after I setup the bot on Bitfinex, it started to send summary notifications **each 5 minutes** (should be once per day!), like this:

`Earnings:`
`None Today`
`None Yesterday`
`Unknown total earnings.`

Immediately after the first loan was closed, the problem stopped. See below:

![image](https://user-images.githubusercontent.com/29162354/29671352-b8d5608a-88bf-11e7-9079-58e0285dc576.png)

**Comment by utdrmac** [comment] 2017-08-24 16:36
Hrm. That's an odd one.

**Comment by utdrmac** [comment] 2017-08-24 16:39
If there's no history in the database, the function `notify_stats` should return immediately (and not send notifications) due to this:

`if (self.get_db_version() == 0) and (self.get_first_timestamp() is not None): `

**Comment by utdrmac** [comment] 2017-08-24 16:49
The "every 5 minutes" is controlled by the main event loop whose sleep time is defined here:

`sleeptimeinactive = 300`

Ah. The issue is that with no lending history, `self.get_first_timestamp()` does return None which fails that logic check and then attempts to give report. Will need to change that logic.

**Comment by utdrmac** [comment] 2017-08-24 17:03
@rnevet Assume user has no history. First iteration of `after_lending` will `update_history` and `notify_status`

last_time_stamp becomes None which then sets to BITCOIN_GENESIS_BLOCK_DATE and sets user_version to 0

We then fetch all history from BITCOIN_GENESIS_BLOCK_DATE to now().

That returns 0 history for new user. This is a correct fetch but the user_version is never updated to indicate we have successfully downloaded all history.

Add this for that check. If 0 history and we attempted to fetch from the beginning, then they have no history, update database ready to use.

If they DO have history before starting the bot, then last_time_stamp still becomes None which then sets to BITCOIN_GENESIS_BLOCK_DATE and sets user_version to 0. Assuming they have lots of history to download, the first count will be greater than 0 and the batch-loop will still run to download remaining history which will still set user_version correctly.

```
@@ -59,7 +72,12 @@ class AccountStats(Plugin):
             last_time_stamp = BITCOIN_GENESIS_BLOCK_DATE
             self.db.execute("PRAGMA user_version = 0")

-        self.fetch_history(self.api.create_time_stamp(last_time_stamp), sqlite3.time.time())
+        count = self.fetch_history(self.api.create_time_stamp(last_time_stamp), sqlite3.time.time())
+
+        # If we attempted to fetch all history and that returns 0, then
+        # there is no history, so we are up to date and can continue.
+        if (count == 0) and (last_time_stamp == BITCOIN_GENESIS_BLOCK_DATE):
+            self.set_db_version(DB_VERSION)
```

**Comment by rnevet** [comment] 2017-08-24 20:57
I'll look into it.

**Comment by pedrofaraco** [comment] 2017-08-27 08:01
It's getting worse. Now happens almost every minute:

![image](https://user-images.githubusercontent.com/29162354/29748099-aa2c6f7a-8ae4-11e7-8ace-871eb453a413.png)

**Comment by utdrmac** [comment] 2017-08-27 16:45
@pedrofaraco Can you apply the code changes I put above and see if that fixes it for you? You'll have to be our tester.

**Comment by utdrmac** [comment] 2017-08-27 17:16
@pedrofaraco You need to add the code above and this code as well to `notify_stats`

```
        if (self.get_db_version() == DB_VERSION) and (self.get_first_timestamp() is None):
            # Database is ready but there are no results
            self.log.log('AccountStats: No history.')
            return
```

**Comment by utdrmac** [comment] 2017-08-27 17:19
@pedrofaraco Here's my full plugin/AccountStats.py with my fix for your issue.

https://www.hastebin.com/evavezasix.py

**Comment by rnevet** [comment] 2017-08-27 20:42
@utdrmac, can you make a PR with that fix?

**Comment by rnevet** [comment] 2017-08-27 21:24
@pedrofaraco could you test this and indicate if it solves the issue?

**Comment by utdrmac** [comment] 2017-08-27 22:54
I'll make a PR if the code fixes his issue

**Comment by pedrofaraco** [comment] 2017-08-28 01:04
@utdrmac, I've been testing your AccountStats.py for the last 60 minutes. So far so good. I'll monitor it closely for the next 24h.

**Comment by pedrofaraco** [comment] 2017-08-28 14:22
It seems the fix solved the issue BEFORE the first loan but created a new one AFTER it. Let's take a look.

I've replaced the file and restarted the bot at 21:01 (local time, so you can follow Telegram's notification times below).

![image](https://user-images.githubusercontent.com/29162354/29777098-32f843fe-8be1-11e7-8b5b-52b51d504f67.png)

As you can see, Earnings notification was been sent each five minutes, until 21:01.

At 21:02, the Summary notification was sent (right after bot was rebooted).

At 22:36, there was an Earnings notification.

At 23:02, a new Summary notification was sent (as expected, since notify_summary_minutes is set to 120).

At 23:07, a new Earnings notification was sent (approx. thirty minutes after the last one). This periodicity continues since then.

![image](https://user-images.githubusercontent.com/29162354/29777512-afe85498-8be2-11e7-8e5d-2f45ebdd8cf9.png)

Since the first loan was already made, I can't reproduce the entire test to assure a new fix will work before the first loan.  But if I setup the bot in a new Bitfinex account (which may occurs in the next few weeks) I'll let you know.

**Comment by utdrmac** [comment] 2017-08-28 15:10
That doesn't make sense. You shouldn't be getting notifications because of these lines:

https://github.com/BitBotFactory/poloniexlendingbot/blob/master/plugins/AccountStats.py#L43-L45

These lines enforce a `report_interval` minimum between notifications. By default this is 86400 seconds (1 day).

Do you have `[ACCOUNTSTATS]` block in your config with a small `ReportInterval` setting?

**Comment by pedrofaraco** [comment] 2017-08-28 16:27
Hummm... I think you are right.

Maybe I've uncommented the ReportInterval directive that brings by default the value 1800. I thought this value was expressed in minutes.

![image](https://user-images.githubusercontent.com/29162354/29782647-c0ed2f6e-8bf3-11e7-93fc-b4108c0e86e8.png)

Maybe is a good idea to change this part of `default.cfg.example` to reflect the 86400 default value.

I don't have access to the environment right now, but I'll check this later.

**Comment by rnevet** [comment] 2017-08-28 18:53
@pedrofaraco I've updated the default.cfg.example to reflect the 86400 default value. ( I missed that when I merged the PR)

**Comment by rnevet** [comment] 2017-08-28 18:54
So otherwise this issue is fixed by the code provided, cool.

**Comment by pedrofaraco** [comment] 2017-08-28 22:56
This is it. I've changed the `ReportInterval` setting and everything is fine. Issue can be closed. Thanks!

**Comment by utdrmac** [comment] 2017-08-28 22:57
@pedrofaraco please don't close this. I need to submit a PR related to this issue for adding the new code that solves the issue outside of correcting the interval.

**Comment by utdrmac** [comment] 2017-08-28 22:59
@rnevet I had actually put the default.cfg.example differently from the default on purpose as 1 sentence above it is stated the default is once per day.

**Comment by rnevet** [comment] 2017-08-28 23:23
@utdrmac  I don't have an objection, it's just confusing as you see... most of the examples contain default values... IMO. Open for discussion.

**Comment by pedrofaraco** [comment] 2017-08-28 23:35
Oh, sorry for closing it @utdrmac!

By the way, I will setup new bots later this week. If you still need any tests regarding this issue, let me know.

**Comment by pedrofaraco** [comment] 2017-08-28 23:43
@rnevet, I agree with you that it's confusing: many other commented settings contain default values and I assumed 1800 was `ReportInterval`'s default value in minutes (yeah, I know that a quick math would made me realize that the right value was 1440).

**Comment by utdrmac** [comment] 2017-09-03 16:43
@rnevet Is this fixed then? I see the HEAD default.cfg.example has the ReportInterval=86400.

@pedrofaraco have you had a chance to set up new bots with no history to see if this is still an issue?

**Comment by rnevet** [comment] 2017-09-03 18:58
Should be fixed, closing.

**Closed by rnevet** 2017-09-03 18:58 UTC
