### ISSUE TITLE
 Error list index out of range makes the bot crash

### ISSUE THREAD

**Issue by SloRunner** [BitBotFactory/poloniexlendingbot#614] opened 2018-02-23 16:20 UTC
```
2018-02-23 17:15:09 Error list index out of range
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 254, in lend_all
    lend_all()
  File "/root/poloniexlend/modules/Lending.py", line 252, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/root/poloniexlend/modules/Lending.py", line 449, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/root/poloniexlend/modules/Lending.py", line 350, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "/root/poloniexlend/modules/Lending.py", line 404, in get_gap_mode_rates
    top_rate = get_gap_rate(cur, top_depth, order_book, cur_total_balance, True)
  File "/root/poloniexlend/modules/Lending.py", line 337, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

v318
 Unhandled error, please open a Github issue so we can fix it!
```

**Comment by JCBauza** [comment] 2018-03-04 23:04
same here. Once this happens then bot stops working. 

2018-03-04 12:10:06 Error list index out of range
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/poloniexlendingbot/modules/Lending.py", line 252, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/poloniexlendingbot/modules/Lending.py", line 449, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/poloniexlendingbot/modules/Lending.py", line 350, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "/poloniexlendingbot/modules/Lending.py", line 410, in get_gap_mode_rates
    top_rate = get_gap_rate(cur, gap_top, order_book, cur_total_balance)
  File "/poloniexlendingbot/modules/Lending.py", line 337, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range

v318
 Unhandled error, please open a Github issue so we can fix it!

**Comment by Evanito** [comment] 2018-03-17 19:12
Duplicate of #566 
Really needs to be handled/fixed

**Closed by Evanito** 2018-03-17 19:12 UTC
Labels: Bug
