### ISSUE TITLE
 Unhandled error, please open a Github issue so we can fix it!

### ISSUE THREAD

**Issue by k0ni** [BitBotFactory/poloniexlendingbot#592] opened 2017-12-07 08:23 UTC
```
Unhandled error, please open a Github issue so we can fix it!
2017-12-07 10:19:59 Error list index out of range
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 249, in lend_all
    lend_all()
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 249, in lend_all
    lend_all()
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 249, in lend_all
    lend_all()
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 247, in lend_all
    usable_currencies += lend_cur(cur, total_lent, lending_balances, ticker)
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 418, in lend_cur
    orders = construct_orders(active_cur, active_bal, active_cur_total_balance, ticker)  # Build all potential orders
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 319, in construct_orders
    top_rate, bottom_rate = get_gap_mode_rates(cur, cur_active_bal, cur_total_balance, ticker)
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 373, in get_gap_mode_rates
    top_rate = get_gap_rate(cur, top_depth, order_book, cur_total_balance, True)
  File "/home/user1/poloniexlendingbot/modules/Lending.py", line 306, in get_gap_rate
    return Decimal(order_book['rates'][i])
IndexError: list index out of range
```

**Comment by laxdog** [comment] 2017-12-14 17:29
Thanks for the bug report @k0ni 

There are a lot of these we need to tidy up. It shouldn't be anything to worry about, the bot should continue after this message.

**Comment by Evanito** [comment] 2018-03-17 18:50
Duplicate of #566

**Closed by Evanito** 2018-03-17 18:50 UTC
