### ISSUE TITLE
Error HTTPSConnectionPool(host='api.bitfinex.com', port=443): Max retries exceeded with url: /v1/credits

### ISSUE THREAD

**Issue by shevah** [BitBotFactory/poloniexlendingbot#553] opened 2017-10-04 07:30 UTC
Hi, 
I get this error quite frequently. Using Bitfinex.

```
 Unhandled error, please open a Github issue so we can fix it!
2017-10-04 06:28:06 Error HTTPSConnectionPool(host='api.bitfinex.com', port=443): Max retries exceeded with url: /v1/credits (Caused by NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x749dd970>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution',)) Requesting https://api.bitfinex.com/v1/credits
Traceback (most recent call last):
  File "lendingbot.py", line 94, in <module>
    Lending.lend_all()
  File "/Desktop/bitfinex/modules/Lending.py", line 224, in lend_all
    total_lent = Data.get_total_lent()[0]
  File "/Desktop/bitfinex/modules/Data.py", line 44, in get_total_lent
    crypto_lent = api.return_active_loans()
  File "/Desktop/bitfinex/modules/Bitfinex.py", line 160, in return_active_loans
    bfx_resp = self._post('credits')
  File "/Desktop/bitfinex/modules/Bitfinex.py", line 116, in _post
    return self._request('post', payload['request'], signed_payload, verify)
  File "/Desktop/bitfinex/modules/ExchangeApi.py", line 29, in new_method
    return method(self, *arg, **kws)
  File "/Desktop/bitfinex/modules/Bitfinex.py", line 109, in _request
    raise ex
```

**Comment by Evanito** [comment] 2017-10-06 00:51
This is probably caused by temporary downtime in your DNS servers.

**Comment by shevah** [comment] 2017-10-06 09:10
Ok, but I can't say I feel that in other services I use

**Comment by laxdog** [comment] 2017-11-17 11:26
Happens all the time in my set up too. It's definitely nothing we can fix in the code.

**Comment by utdrmac** [comment] 2017-11-17 17:00
It would be nice if the code properly caught this exception rather than barfing out a stack trace each time.

**Comment by laxdog** [comment] 2017-12-05 15:23
OK, I'll remove the label and it can be looked at.

**Comment by rnevet** [comment] 2017-12-05 23:23
Can't we just get Polo ip and then use it? so we don't do too much DNS resolving?

**Comment by Evanito** [comment] 2018-03-18 19:26
Related: #617

**Closed** 2018-03-19 01:10 UTC
