### ISSUE TITLE
Auto transfer from Lending balance to Exchange balance above a certain threshold

### ISSUE THREAD

**Issue by Steve184** [BitBotFactory/poloniexlendingbot#424] opened 2017-07-12 11:30 UTC
Hi,

This bot is really great !
This one is not a bug but rather a suggestion to improve the program.

In the same philosophy as the functionality that automatically transfers balance from Exchange to Lending, it would be great to have a feature that transfers coins above a certain threshold every X days from Lending to Exchange .

For instance, if my threshold is 1.5 BTC and my lending balance is 1.55 BTC, then the bot would automatically transfer 0.05 BTC back to the exchange balance X days after the last Lending > Exchange transfer. 

That way it would be easier to withdraw from BTC account, for instance on a monthly basis.

Cheers !

**Comment by rnevet** [comment] 2017-07-12 15:32
I think this is related to https://github.com/BitBotFactory/poloniexlendingbot/issues/371.

**Comment by Evanito** [comment] 2017-07-25 22:50
Duplicate of #371 

Will, however include that raw amounts should be included as well as percentages.

**Closed by Evanito** 2017-07-25 22:50 UTC
Labels: Duplicate
